use_frameworks!

platform :ios, '8.0'

target 'XALFrameworks_Example' do
  pod 'XALFrameworks', :path => '../'

  
end
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['BITCODE_GENERATION_MODE'] = 'bitcode'
      config.build_settings['ENABLE_BITCODE'] = 'YES'
    end
  end
end
